---
all:
  children:
    management:
      hosts:
        mgmt01.example.edu:
        ansible01.example.edu:
    internal:
      hosts:
        login01.example.edu:
        login02.example.edu:
    restricted:
      hosts:
        compute01.example.edu:
        compute02.example.edu:
    public:
      hosts:
        web01.example.edu:
